server:
  port: 8080
  servlet:
    #项目路径
    context-path: /stdc-visual
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #设置外部路径为静态目录
  web:
    resources:
      static-locations: file:./static
  #文件上传配置
  servlet:
    multipart:
      #单个文件上传最大值
      max-file-size: 1500MB
      #单词请求总数据最大值
      max-request-size: 1500MB
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.255.102.226:13306/stdc-visual?serverTimezone=UTC&useSSL=false&characterEncoding=utf-8
    username: root
    password: '000925'
    #最大连接数
    max-active: 1000
    #连接池的最大阻塞等待时间
    max-wait: 60000
    #连接池的最小空闲连接数
    min-idle: 10
    #Destroy线程会检测连接的间隔时间
    time-between-eviction-runs-millis: 60000
    #检测sql
    validation-query: select 1
    # 申请连接的时候检测，若空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    test-while-idle: true
    # 申请连接时执行validationQuery检测连接是否有效
    test-on-borrow: true
    # 归还连接时执行validationQuery检测连接是否有效
    test-on-return: true
#
  #redis配置
  redis:
    host: 10.255.111.135
#    host: 127.0.0.1
    port: 6379
    database: 5
    password: stdc@000925
    lettuce:
      pool:
        #连接池最大连接数
        max-active: 8
        #连接池最大阻塞等待时间
        max-wait: -1
        #最大空闲连接
        max-idle: 10
        #最小空闲连接
        min-idle: 5
#日志配置文件地址
logging:
  config: classpath:logback-spring.xml
  level:
    com:
      alibaba:
        druid: DEBUG
stdc:
  #swagger信息
  swagger:
    title: stdc 可视化服务
    description: 这是一个可视化服务
    version: 0.0.1
    enable: true
#权限
  security:
    #是否开启权限
    enable: true
    # own:自己权限 cas:cas统一权限
    source: cas
    #登录状态过期时间  默认是俩小时：7200000
    timeout: 7200000
    #统一权限,单点登录远程请求接口
    sso:
      cas:
        #CAS服务地址
        service-url: http://10.255.111.93:18527/sign/authz/cas
        #通过用户名获取用户-角色信息
        role-url: http://10.255.111.93:18526/eiam-mgt/getInfo/info/getUserRolesByUserName
  #预览过期时间
  previewtime: 600000
  #接口配置
  api:
    #报文加密配置
    crypto:
      #启用报文加密配置
      enabled: true
      #使用AesUtil.genAesKey()生成
      aes-key: O2BEeIv399qHQNhD6aGW8R8DEj4bqHXm
  #日志配置
  log:
    #开启日志配置
    request:
      enable: true
    #日志文件存储地址
    path: D:\ProjectForWork\DocumentProject\Stdc-Java\log\stdc-visual-log
#开启swagger增强模式
knife4j:
  enable: true
#jdbc数据jar包地址
driver:
  path: G:\work\java\gitlab\stdc-datav-java\stdc-visual-service\stdc-visual-dynamic\src\main\resources\drivers
#新建大屏导入psd文件配置路径
python:
  exe-path: E:/py3.8/python.exe
  python-file-path: E:/Desktop/psdTest/Psd_tool.py
  cache-psd-path: E:/Desktop/psdTest/
  #docker容器映射的主机ip和端口号
  api: http://10.103.27.55:18021
#文件对象存储配置
oss:
  minio:
    enable: true
#    endpoint: http://10.103.27.55:9000
#    endpoint: http://10.255.102.116:9000
    endpoint: http://10.255.111.135:9000
    access-key: stdc@admin
    secret-key: VW5pdHRlY0AxMjMh
    file-type-default: default
    file-type-svg: svg
    file-type-font: font
    file-type-css: css
    file-type-back: back
    file-type-thumbnail: thumbnail
    stdc-topology-bucket: stdc-topology
#cmp对接
cmp:
  version: http://10.200.90.11:31001/configManage/v1/releases/version
  data: http://10.200.90.11:31001/configManage/v1/releases/data