import { KEY_COMPONENT_NAME } from './variable'
export default {
  name: KEY_COMPONENT_NAME,
  echart: [
    'common',
    'map',
    'pictorialbar',
    'wordcloud',
    'scatter',
    'bar',
    'line',
    'pie',
    'gauge',
    'funnel',
    'radar',
    'sankey',
    'atepicker',
    'basicarea',
    'line-bar',
    'crosstable',
    'progressView',
    'progressBar',
    'ZebraProgressBar',
    'delayImg',
    'dataStorage',
    'flv',
    'stereoscopicBar',
    'switchMultiple',
    'newPictorialBar',
    'PeakBar',
    'scrollRanking',
    'eventRankingList',
    'threeModel',
    'queryBox',
    'domModule',
    'liquidFill',
    'biaxlinebar',
    'textRankingList',
    'relationshipDiagram',
    'roadMap',
    'customVue'
  ],
  highChart: ['stereoscopicPie'],
}
